main:
  - name: Home
    url: /
    weight: 10

  - name: CV
    url: uploads/resume.pdf
    weight: 11

  - name: Publications
    url: publications/
    weight: 13

  - name: Courses
    url: courses/
    weight: 14